---

- name: Ensure pseudo filesystems are unmounted
  ansible.posix.mount:
    path: "{{ dbstrp_mountpoint }}/{{ item }}"
    state: unmounted
  with_items: "{{ pseudo_fs|reverse }}"

- name: Ensure {{ dbstrp_mountpoint }}/boot/efi is not mounted
  ansible.posix.mount:
    path: "{{ dbstrp_mountpoint }}/boot/efi"
    state: unmounted

- name: Check for mounted targets
  command: mount
  register: _existing_mounts

- name: Unmount anything residual in target directory
  command: umount -Rfl {{ dbstrp_mountpoint }}
  when: "dbstrp_mountpoint in _existing_mounts.stdout"

- name: Unmount any residual zfs mounts
  command: zfs umount -f -a
  when:
    - "dbstrp_mountpoint in _existing_mounts.stdout"
    - "'type zfs' in _existing_mounts.stdout"

- name: Remove any residual directories in {{ dbstrp_mountpoint }}
  file:
    path: "{{ dbstrp_mountpoint }}"
    state: absent

- name: Gather facts about ZFS pools
  community.general.zpool_facts: properties='name'

- name: Export ZFS pools
  command: zpool export -f -a
  loop: '{{ ansible_zfs_pools }}'
  loop_control:
    label: "{{ item.name }}"

- name: Deactivate volumes
  lvol:
    active: no
    lv: "{{ volume.lvm.lv|default(volume.lvm.thinpool) }}"
    vg: "{{ volume.lvm.vg }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.lvm.vg }}/volume.lvm.lv|default(volume.lvm.thinpool) }}"
  loop: "{{ lvm|reverse|list }}"
  when: >
    volume.lvm is defined and (
    volume.lvm.lv is defined or volume.lvm.thinpool is defined)

- name: Gather luks targets
  command: dmsetup info -c -o Name --noheadings
  register: _targets

- name: Close any open luks tagets
  command: "cryptsetup luksClose /dev/mapper/{{ item }}"
  when: "not item == 'No devices found'"
  loop: "{{ _targets.stdout_lines }}"

- name: stop raid devices
  command: "mdadm --stop --scan"
