---

- name: Create ext4 filesystems
  command: >
    mkfs.ext4 {{ item.value['mkfs_options']|default('-b 4096') }} {{ item.key }}
  with_dict: "{{ _tgt_devices }}"
  when: >
    not item.value['encrypt']|default(False) and item.value['fs']|default('undefined') == 'ext4'

- name: Create xfs filesystems
  command: >
    mkfs.xfs -f {{ item.value['mkfs_options']|default('-b size=4096 -s size=4096') }}
    {{ item.key }}
  with_dict: "{{ _tgt_devices }}"
  when: >
    not item.value['encrypt']|default(False) and item.value['fs']|default('undefined') == 'xfs'
